name: Continuous Integration

on:
  push:
    branches:
      - 'hotfix-*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  code-integrity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint check
        run: bun lint

      - name: Type check
        run: bun typecheck

      - name: Build check
        run: bun build
